# Generated by Django 3.2.7 on 2021-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan', '0003_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='stage1_file',
            field=models.FileField(upload_to='static/submissions/stage 1'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage2_file',
            field=models.FileField(upload_to='static/submissions/stage 2'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage3_file',
            field=models.FileField(upload_to='static/submissions/stage 3'),
        ),
    ]
