# Generated by Django 3.2.7 on 2021-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan', '0004_auto_20211019_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='stage1_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage2_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage3_file',
            field=models.FileField(upload_to=''),
        ),
    ]
