# Generated by Django 3.2.7 on 2021-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan', '0005_auto_20211019_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='stage1_file',
            field=models.FileField(upload_to='submissions/stage1'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage2_file',
            field=models.FileField(upload_to='submissions/stage2'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='stage3_file',
            field=models.FileField(upload_to='submissions/stage3'),
        ),
    ]
